// Code generated by test fixture; DO NOT EDIT.

package rules

func generated() {
	items := []struct {
		Name string
	}{
		{Name: "short"}, {
			Name: "long enough to require the multiline sibling layout rule",
		},
	}
	_ = items
}
